### ISSUE TITLE
Add the ability to inject data WITHOUT dropping the connection

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/CitadelCore#49]
Right now we can only inject data and then drop the connection. We ideally would like to be able to inject and keep the connection alive.

**Comment by vincenthawke** [comment]
What is the technical reason that the connection is dropped after the data is modified?

**Comment by TechnikEmpire** [comment]
No technical reason. The original purpose/design of the api was to give a binary choice of allowing or dropping. Setting the payload was designed to display a block page or similar content when deciding to drop.

Development has moved to private repos so issues like this won't be addressed here.
