### ISSUE TITLE
HttpMessageInfo.StatusCode wrong value

### ISSUE THREAD

**Issue by vdhong** [TechnikEmpire/CitadelCore#59]
Hello,
I access a not found link (e.g. http://phongdaotao.com/test.aspx) and browser show error code 404 but when I get StatusCode of HttpMessageInfo it return 200 (OK). I think CitadelCore not initialize this field yet. Then I take a look in CitadelCore source code and yeah that field was not initialized. Look at line 362 in FilterHttpResponseHandler.cs file you create HttpMessageInfo object but not assign value for StatusCode field.
```
var responseMessageNfo = new HttpMessageInfo
                    {
                        Url = reqUrl,
                        IsEncrypted = context.Request.IsHttps,
                        Headers = response.ExportAllHeaders(),
                        MessageProtocol = MessageProtocol.Http,
                        MessageType = MessageType.Response,
                        RemoteAddress = context.Connection.RemoteIpAddress,
                        RemotePort = (ushort)context.Connection.RemotePort,
                        LocalAddress = context.Connection.LocalIpAddress,
                        LocalPort = (ushort)context.Connection.LocalPort
                    };
```

**Comment by TechnikEmpire** [comment]
Thank you for reporting! I'll patch this tonight
