### ISSUE TITLE
HTTPS exception on TlsSniConnectionAdapter.cs::InnerOnConnectionAsync() 

### ISSUE THREAD

**Issue by francescopaolopassaro** [TechnikEmpire/CitadelCore#65]
Hello!
 congratulations for this project!I'm very happy to use it,but i've this problem on : 
  VisualStudio 2017 IDE
  Windows 10 X64 Professional
on all HTTPS request ...

Thank you! if I can useful I'm available
 
Log error :
Not filtering application C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe destined for 443
Filtering application C:\Program Files (x86)\Google\Chrome\Application\chrome.exe destined for 443
ERRO: Failed to complete client TLS handshake because of unknown exception.      TlsSniConnectionAdapter.cs::InnerOnConnectionAsync() #149
ERRO: Impossibile riconoscere le credenziali fornite al pacchetto   in System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   in System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   in System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
   in System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   in System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   in System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   in System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   in System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   in System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   in System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   in System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   in System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   in System.Net.Security.SslStream.<>c__DisplayClass28_0.<AuthenticateAsServerAsync>b__0(AsyncCallback callback, Object state)
   in System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   in System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   in CitadelCore.Net.ConnectionAdapters.TlsSniConnectionAdapter.<InnerOnConnectionAsync>d__7.MoveNext()
         From TlsSniConnectionAdapter.cs::InnerOnConnectionAsync() #150

Here expetion code : 

                                context.Features.Set<ITlsConnectionFeature>(new TlsConnectionFeature
                                {
                                    ClientCertificate = sslStream.RemoteCertificate?.ToV2Certificate()
                                });
                               
                                return new HttpsAdaptedConnection(sslStream);
                            }
                            catch (Exception err)

**Comment by TechnikEmpire** [comment]
Any chance that you have another program installed that is doing HTTPS filtering? Most antivirus these days do this. Let me know, I'll look into more in depth. Am I right that the error is:

`The credentials supplied to the package can not be recognized`?

Because a quick search shows this is an error with the signing certificate. Or, you're not running the app as admin possibly?

**Comment by francescopaolopassaro** [comment]
o.s. is cleaned system:
windows pro 10
visualstudio 2017
sql server 2017 express and Sqllite studio
chrome
 ... windows firewall is off and windows defender off...
All traffic https i've this exception... please see my screenshot
![error](https://user-images.githubusercontent.com/19148990/46920123-bec96780-cfe9-11e8-8b14-54a3ce4fbe88.jpg)

**Comment by francescopaolopassaro** [comment]
> o.s. is cleaned system:
> windows pro 10
> visualstudio 2017
> sql server 2017 express and Sqllite studio
> chrome
> ... windows firewall is off and windows defender off...
> All traffic https i've this exception... please see my screenshot
> ![error](https://user-images.githubusercontent.com/19148990/46920123-bec96780-cfe9-11e8-8b14-54a3ce4fbe88.jpg)

and  visual studio debug in admin rights

**Comment by francescopaolopassaro** [comment]
hi,
another test case : Generated regular CA/root with autorithy name / cn ... i've tested with another proxy on ssl https tunnel is ok... but i've excepetion with this source code...  

var cfg = new ProxyServerConfiguration
            {
                AuthorityName = {Authority from CA },
                FirewallCheckCallback = OnFirewallCheck,
                NewHttpMessageHandler = OnNewMessage,
                HttpMessageWholeBodyInspectionHandler = OnWholeBodyContentInspection,
                HttpMessageStreamedInspectionHandler = OnStreamedContentInspection
            };

**Comment by TechnikEmpire** [comment]
You're generating the authority externally? Does the unmodified example throw the exception you showed before?

**Comment by TechnikEmpire** [comment]
Something is really off here, because you should not be getting a QUIC protocol error. QUIC packets are dropped, which forces Chrome to fallback to proper HTTP/S. This looks like a wreck. Looking forward to more information.

**Comment by francescopaolopassaro** [comment]
I make a test creating the certificates but then I saw in the code that there is a generation and overwriting ... however I did not make any changes ... however it is certainly a certificate problem .. I tried forcing the code to use a very specific certificate the exception has been removed but obviously it has not solved anything .. I have done the rollback of the code

**Comment by TechnikEmpire** [comment]
Ok so definitely do not create a cert. The proxy generates one every time, as you have seen. Plus, there's a lot more to this then installing a custom cert. Almost surely the private key would not be bundled. Anyway there's no sense in speculation because this library is designed explicitly NOT to work with external certificates.

So, rolling back the code to be exactly as this source, does the example work? It ought to, there's a rather large community using this library and I have not heard of such a huge issue before.

**Comment by francescopaolopassaro** [comment]
ive recovered all source code with ufficial repository.. ive exception... I already knew the library and used it before .. I did not know the whole process now for the bug I'm studying .. first with another clean installation like this with windows 8.1 I never found anything ... now I can not remember the version... ive only so cleaned on developement.. without antivirus or firewall..

**Comment by francescopaolopassaro** [comment]
certificate I have only run tests to see if changing the bug was presented ... the certificate obviously using a valid one with a private key.... ive cleaned exception but chrome or another browser ive warning for the certificate

**Comment by francescopaolopassaro** [comment]
for anything I am at your disposal and if you want in private I can send you my private contacts if you can help

**Comment by TechnikEmpire** [comment]
Can you do me a favor, and clone [CitadelCore.Windows](https://github.com/TechnikEmpire/CitadelCore.Windows) on to a different computer, then compile and run the example program. If it works for you on another computer, then you'll know that it's an issue with your current machine.

If not, I'd be concerned that your SSL connections are being intercepted by something else.

**Comment by TechnikEmpire** [comment]
You can email me at info[at]technikempire.com.

**Comment by TechnikEmpire** [comment]
You are using [CitadelCore.Windows](https://github.com/TechnikEmpire/CitadelCore.Windows), right? I hope you're not trying to implement this library (CitadelCore) yourself!

**Comment by francescopaolopassaro** [comment]
i ve compiled software with another pc with windows 10 x64 i ve bug(cleaned so visualstudio 2017 pro sql server) .. with another library is ok on ssl is ok with certificate generated with similar code and library used in this good library...

**Comment by TechnikEmpire** [comment]
I'm not sure what to say. I am unable to reproduce this. There's two organizations, one with a very large user base that relies on this software daily and I have not heard a report like this. I am actively developing this library and testing it, cannot see any issue like this.

Take a screenshot of the trust chain please. Like this:

![image](https://user-images.githubusercontent.com/11234763/47032966-9f455280-d141-11e8-9f12-e3f92e581467.png)

**Comment by TechnikEmpire** [comment]
Are you running this app as a .NET FULL application, or as .NET core? I assume .NET FULL because you said you restored the code to the original source version.

**Comment by TechnikEmpire** [comment]
The common issue behind the error you're seeing has to do with the private key not being written to the certificate.

I am not writing the private key to the certificate, because it would be a brutal security risk to simply enable any and all apps on the machine to be able to decrypt traffic generated and intercepted by the proxy. 

The fact that this error is occurring tells me that something is seriously wrong outside of the software itself. What is almost surely happening is that a different certificate, which the private key generated inside the software does match, is being loaded and/or being used to encrypt in the application pipeline. That runs seriously against the design of this software.

Until further evidence can be supplied that the issue is with this library, I'm marking this bug as "external" and "wontfix", as I am unable to reproduce it, and the information supplied suggests to me that the issue is in fact external and not an issue with this library.

**Comment by francescopaolopassaro** [comment]
unfortunately yesterday I had an accident and I was invested as soon as possible I respond to everything .. comunqie libraries to restore .. my recovery is drastic start from the beginning unload all repository again erasing everything that was before avoiding different configurations on the libraries. as soon as possible I will answer you to other things ... but I'm sure it does not depend on external sources I repeat they are clean windows installations

**Comment by TechnikEmpire** [comment]
I'm sorry to hear that (re: your accident).

Can you take a shot of the trust chain please?

Also, you can override this:

https://github.com/TechnikEmpire/CitadelCore/blob/master/CitadelCore/Net/Proxy/ProxyServer.cs#L134

in two ways. You can extend the ProxyServer class and override the callback, or you can directly hook the global .NET callback into your own handler inside your program. Do it the exact same way as the ProxySever class does, or change the `+=` into a `=` and it will override no matter what.

In the override, like this:

https://github.com/TechnikEmpire/CitadelCore/blob/master/CitadelCore/Net/Proxy/ProxyServer.cs#L289

You can put a breakpoint and inspect why your SSL connections are really failing.

I appreciate that you are testing on "new" machines, but you could easily be on a network that is being manipulated, or worse, an internet service provider that is manipulating these connections. So, I need to see the trust chain, either through chrome, or you copy and pasting debug output from hooking that callback as I described.

**Comment by francescopaolopassaro** [comment]
I have replicated the problem as it occurs and is a compatibility between windivert & vmware. I checked all the Vmware forums and I did not find any reports for anomalies between Vmware Player Workstation and the HTTPS / SSL port. It has been reported a problem but on Vmware Workstation because it has the function of sharing the virtual machine with the port 443 / HTTPS. I checked through netstat anyway if there is something listening on the 443 and I have nothing .. I have disabled all services including those of vmware. With all the tests I've done I checked windivert that the dlls in this package remain locked even after the debugging is finished. So according to me if there is a problem on the 443 for the SSL / HTTPS tunnel at least we should investigate windivert and vmware / surely maybe better manage the exception.
I tested the libraries and the project on other physical machines, obviously I did not find any anomaly.
Other data with Windows 8.1 on vmware player same version and configuration I found nothing.
Unfortunately I'm injured and I can not work a lot. But I think we should investigate the problem that occurs on vmware.
The configurations have been verified all on vmware I have also configured the gateway and the dns as advised in other similar issues ... but without success .... I think the ticket should be varied in VMware Issues.Just get other information I will write to you as I promise to send you my private contacts.
Best wishes

**Comment by TechnikEmpire** [comment]
It's not the port.

Download and use virtualbox. I have 0 issues developing with this library under virtualbox.

**Comment by TechnikEmpire** [comment]
Supporting specific virtual machines is not within my scope. WinDivert relies on low-level network drivers and some vm's don't get this right. The end goal of this library is to be executed on real, end-consumer machines.

Please try virtualbox or run the program on your *real* computer. If it functions on a real machine, I will close this ticket.

**Comment by TechnikEmpire** [comment]
Closing this as being an issue with VMware.

**Comment by francescopaolopassaro** [comment]
hello i ve. problem with virtualbox (last version) .. i ve migrated new machine s. o cleaned visual studio 2017 e windows 10 pro... with physical machine is ok.. you've nat or bridge on your machine? s. o?.. i ve tested with three different pc configuration...

**Comment by TechnikEmpire** [comment]
I think I was using nat. I'll double check my configuration tonight and get back to you.

**Comment by francescopaolopassaro** [comment]
thanks thanks a lot!!!

**Comment by TechnikEmpire** [comment]
![image](https://user-images.githubusercontent.com/11234763/47415789-4a599b80-d742-11e8-96d0-81cf5185e04c.png)

Turns out it was bridged.

**Comment by TechnikEmpire** [comment]
![image](https://user-images.githubusercontent.com/11234763/47415824-5cd3d500-d742-11e8-9a2c-a18dd0b028fe.png)
