### ISSUE TITLE
Is it possible to modify response body?

### ISSUE THREAD

**Issue by UlyssesWu** [TechnikEmpire/CitadelCore#72]
Sorry if I've asked a stupid question. When I tried to modify the response body:

        private static void OnWholeBodyContentInspection(HttpMessageInfo messageInfo)
        {
            if (messageInfo.Body.Length > 0)
            {
                var htmlResponse = Encoding.UTF8.GetString(messageInfo.Body.ToArray());
                Console.WriteLine($"RECV BODY: {htmlResponse}");
                 var newBody = Encoding.UTF8.GetBytes("Hello World!");
                 messageInfo.CopyAndSetBody(newBody, 0, newBody.Length, messageInfo.BodyContentType);
                 messageInfo.ProxyNextAction = ProxyNextAction.AllowButRequestContentInspection;
            } 
        }

(There is no example code about how to modify the response body. If it can't, there should be a comment.)
The body is not modified actually. I still received the original body.
When I looking into the code, it seems that the original body is always kept and the `messageInfo.Body` is not used. Why?

https://github.com/TechnikEmpire/CitadelCore/blob/a542e3eced9cbcf1a2c1fe7700b62a2f0734ebea/CitadelCore/Net/Handlers/FilterHttpResponseHandler.cs#L477-L530

I tried to clone the code and make some change by myself but strangely, the compiled dll do not work as expect - the `NewHttpMessageHandler` will not be triggered.

**Comment by UlyssesWu** [comment]
I added a line `responseBody = responseMessageNfo.Body.ToArray();` and it seems works.

> the NewHttpMessageHandler will not be triggered.

It's because my antivirus blocked it, fixed by closing all antivirus softwares.

**Comment by TechnikEmpire** [comment]
@UlyssesWu It's presently not possible to modify it AND keep the stream open. You definitely can set your own body when closing the connection. You need to set the next action to `DropConnection`. Also, you can use the `CopyAndSetBody` method on the `HttpMessageInfo` object if you need that object to preserve the memory of the message body.

Remember that the `Memory` and `Span` objects in .NET are weak references. So if you assign to the `Body` object and let the byte array go out of scope, it will be invalid.

Also, yes, A/V software can be known to conflict with `WinDivert`, the underlying driver for Windows. You may need to disable internet filtering in your A/V software for WinDivert to function correctly.

**Comment by TechnikEmpire** [comment]
Also see https://github.com/TechnikEmpire/CitadelCore/issues/49

However, since this repo is in a feature freeze, it most likely won't be added publicly. PR's are welcome though.
