### ISSUE TITLE
Support for Windivert 2.0

### ISSUE THREAD

**Issue by gocict** [TechnikEmpire/CitadelCore#75]
First of all, thank you for creating a great tool. Windivert has released version 2.0 so do you have any plan to support Windivert 2.0 with CitadelCore?

**Comment by TechnikEmpire** [comment]
Development of citadelcore and citadelcore.windows has moved closed source. Im writing my own wfp driver because I have seen reports that even with batching in 2.0, some services suffer greatly still. I will upgrade my project WinDivertSharp to 2.0 eventually but that's low priority.

**Comment by gocict** [comment]
Thanks for your reply. I think the current CitadelCore is enough for me.

**Comment by TechnikEmpire** [comment]
There may be remnant bugs I fixed since this last commit but I'm not sure. If something comes up that you get stuck on let me know.

**Comment by TechnikEmpire** [comment]
Actually now that I think about it, I think there's a memory leak in the winapi pinboke signatures in citadelcore.windows.

**Comment by gocict** [comment]
Ah, I have a question, CitadelCore currently do not support capturing packets of Wifi hotspot feature on Windows?

**Comment by TechnikEmpire** [comment]
CitadeCore captures off the network layer. IIRC you'd need to capture the forward layer as well. You'd have to modify the diversion code in the CitadelCore.Windows project.

**Comment by TechnikEmpire** [comment]
https://github.com/TechnikEmpire/CitadelCore.Windows/blob/master/CitadelCore.Windows/Diversion/WindowsDiverter.cs

**Comment by gocict** [comment]
Thank you, I will try my best to understand the code!

**Comment by gocict** [comment]
Excuse me sir, CitadelCore works perfectly on my machine and other Windows 10 machine but in some Windows 10 x64 it got this error:
![Untitled](https://user-images.githubusercontent.com/46121759/59145339-80ffd000-8a0c-11e9-8f65-3db22befbfd9.png)
And I need to turn off Driver Signature Enforcement to solve. Is it a bug?

**Comment by TechnikEmpire** [comment]
No idea. That's a windivert issue. Please look up the basil/divert project on github and report there.

**Comment by TechnikEmpire** [comment]
Also I'm not supporting upgrades to windivert 2.0. I'm phasing that driver out.
