### ISSUE TITLE
Error when upload file to Google Drive

### ISSUE THREAD

**Issue by gocict** [TechnikEmpire/CitadelCore#76]
Hi sir!
I'm using CitadelCore 4.2.3 and I got an error when upload file to Google Drive.
Can you have a look at this? Thanks!
![error 1](https://user-images.githubusercontent.com/46121759/63487396-381ccb00-c4d5-11e9-8ee0-81486ff898b7.PNG)

![error 2](https://user-images.githubusercontent.com/46121759/63487406-40750600-c4d5-11e9-86ac-0ffb19420ea0.PNG)

**Comment by TechnikEmpire** [comment]
Do you happen to work at Zorus? There is no issue with file uploads unless you're uploading and inspecting a file that exceeds 128 megs. Its hardcoded in the http bridge lass. Change the constant.

**Comment by TechnikEmpire** [comment]
I've tested this like yesterday. Although to be fair, I tested it on my closed source version, which is developed actively while this is not. It could be a kestrel issue you need to fix.

All the best.
